[metadata]
authour = "Skye"
name = "thetasigma"

[colors]
foreground = "#FFD9FF"
background = "#04040C"

cursor_bg = "#B0A0EA"
cursor_fg = "#04040C"
cursor_border = "#B0A0EA"

selection_fg = "#F9FFF9"
selection_bg = "#4C146C"

scrollbar_thumb = "#D7A0FE"

split = "#2C144C"

ansi = [
  "#04040C",
  "#FE81BE",
  "#84DFCF",
  "#FEA0DF",
  "#84CEEF",
  "#D790FE",
  "#84BEFF",
  "#FFD9FF",
]
brights = [
  "#4A495A",
  "#FE81DE",
  "#84EFCF",
  "#FE90EF",
  "#84CEFF",
  "#C8A1FE",
  "#84CEFF",
  "#F9FFF9",
]
