[metadata]
authour = "Skye"
name = "thetasigma"

[colors]
foreground = "#FFE7FE"
background = "#100014"

cursor_bg = "#B0A0EA"
cursor_fg = "#100014"
cursor_border = "#B0A0EA"

selection_fg = "#F9FFF9"
selection_bg = "#4C146C"

scrollbar_thumb = "#D7A0FE"

split = "#2C144C"

ansi = [
  "#100014",
  "#FE81BE",
  "#8ADCFF",
  "#FFB0EF",
  "#74B5FF",
  "#D8B0FE",
  "#88CCFF",
  "#FFD7FE",
]
brights = [
  "#4A495A",
  "#FEB1FE",
  "#8ADFFF",
  "#FFC0EF",
  "#98CEFF",
  "#D9C0FE",
  "#8ADCFF",
  "#FFE7FE",
]
